export const items =  [
    {
      id: 1,
      category: 'mobiles',
      title: "Snake Plant",
      imgSrc: 'https://www.plantandflowerinfo.com/images/sansevieria-houseplant.jpg',
      amazonLink: 'https://amzn.to/3PuckZp',
      description: 'An easy houseplant, Snake Plant does not need much care. Will do best in very bright light, even some morning sun. One of the better houseplants for beginners.',
      price: '89999',
    },
    {
      id: 5,
      category: 'laptops',
      title: "Peace Lily",
      imgSrc: 'https://www.plantandflowerinfo.com/images/peace-lily-houseplant.jpg',
      amazonLink: 'https://amzn.to/3EzeQaC',
      description: 'Peace Lily is an easy house plant to grow but will wilt quickly if let to dry too much. Will produce white spathes if light is adequate.',
      price: '49999',
    },
    {
      id: 7,
      category: 'tablets',
      title: "Golden Pothos",
      imgSrc: 'https://www.plantandflowerinfo.com/images/pothos-houseplant.jpg',
      amazonLink: 'https://amzn.to/3ZeNRdY',
      description: 'A popular house plant, it will trail over the edge of the pot or climb a trellis or pole. Medium to bright light is best. Easy care house plant.',
      price: '29999',
    },
    {
      id: 2,
      category: 'mobiles',
      title: "Cast Iron Plant",
      imgSrc: 'https://www.plantandflowerinfo.com/images/cast-iron-house-plant.jpg',
      amazonLink: 'https://amzn.to/44MiYi6',
      description: 'Cast Iron plant can be grown indoors or outdoors. It will thin in indoor light but they are pretty hardy plants. I grow them on my porch and patio. They can be left out in the cold weather, too!',
      price: '79999',
    },
    {
      id: 6,
      category: 'tablets',
      title: "Nephthytis",
      imgSrc: 'https://www.plantandflowerinfo.com/images/nephthytis-houseplant.jpg',
      amazonLink: 'https://amzn.to/3RabsdH',
      description: 'Nephthytis is an easy houseplant to care for and grow. Will do best with bright, indirect light. Will tolerate lower light levels.',
      price: '19999',
    },
    {
      id: 3,
      category: 'mobiles',
      title: "ZZ House Plant",
      imgSrc: 'https://www.plantandflowerinfo.com/images/zz-plant-indoor-house-plant300250.jpg',
      amazonLink: 'https://amzn.to/3r6XJtv',
      description: 'This is the nickname for the Zamioculcas zamifolia. ZZ Plant has become quite popular and is easy to care for.',
      price: '69999',
    },
    {
      id: 4,
      category: 'laptops',
      title: "Pachira Plant",
      imgSrc: 'https://www.plantandflowerinfo.com/images/pachira-indoor-house-plant300250.jpg',
      amazonLink: 'https://amzn.to/44JsK4r',
      description: 'Quite a popular novelty plant, the Pachira plant is known by the common name of Money Tree. Usually has a braided trunk. Easy care.',
      price: '29999',
    },
    {
      id: 9,
      category: 'tablets',
      title: "Arboricola",
      imgSrc: 'https://www.plantandflowerinfo.com/images/arboricola-braid-plant.jpg',
      amazonLink: 'https://amzn.to/3Pdsh4F',
      description: 'This is a braided trunk Arboricola. Arboricola can also have a single trunk, and it is very often grown in a bush form, with multiple stems growing from the soil.',
      price: '49999',
    },
    {
      id: 8,
      category: 'laptops',
      title: "Croton",
      imgSrc: 'https://www.plantandflowerinfo.com/images/croton-plant-in-white-pot.jpg',
      amazonLink: 'https://amzn.to/3r9rvhm',
      description: 'Croton is a colorful houseplant. Easy to care for once you have successfully acclimated to your home environment.',
      price: '89999',
    },


  ]